name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Verify Docker Installation
        run: docker --version

      - name: Verify Docker Compose Installation
        run: docker-compose --version
      - name: Build env
        run: |
          touch docker-compose/limbo-dev/.env docker-compose/limbo-dev/db.env
          echo ${{ secrets.MOCK_DJANGO }} >> docker-compose/limbo-dev/.env
          echo ${{ secrets.MOCK_DB }} >> db.env
          cat db.env
      - name: Build the Docker image
        run: make build target="limbo db"
      - name: Unittest
        run: make debug
